from modules.gender.views import *
from modules.tags.views import *
from modules.department.views import *
from modules.country.views import *
from modules.province.views import *
from modules.district.views import *
from modules.commune.views import *
from modules.village.views import *
from modules.job.views import *
from modules.job_application.views import *
from modules.dashboard.views import *
from modules.menu.views import *

# module to frontend
from modules.contact_me.views import *
from modules.social.views import *
from modules.mycore.views import *
from modules.project.views import *
from modules.filter.views import *
from modules.info.views import *
from modules.career.views import *
from modules.certification.views import *
from modules.study.views import *
from modules.skill.views import *
from modules.teach_stack.views import *
from modules.story.views import *
from modules.message.views import *

from modules.user.views import *
from modules.file_upload.views import *
from modules.notification.views import *
from modules.company.views import *
from modules.reset_attempt.views import *
from modules.reset_password.views import *
from modules.import_file.views import *
from modules.export_file.views import *
