from .api_token.views import *
from .branch.views import *
from .company.views import *
from .dashboard.views import *
from .module.views import *
from .menu.views import *
from .notification.views import *
from .role.views import *
from .role_delegation.views import *
from .store.views import *
from .sync_data.views import *
from .sync_setting.views import *
from .system_date.views import *
from .system_setting.views import *
from .user.views import *
from .websockets.views import *
from .workflow.views import *
